stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t my-node-app .

test_job:
  stage: test
  script:
    - npm install
    - npm test

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to staging"
