trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    docker build -t my-node-app .
  displayName: 'Build Docker Image'

- script: |
    echo "Deploying to staging environment"
  displayName: 'Deployment step'
